# Generated by Django 3.1 on 2025-05-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
